remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: League of Legends - Game Analysis and Role Prediction
description: DSC 80 Final Project

url: https://v1ct0rp.github.io
baseurl: /League-of-Legends-Game-Analysis

color_scheme: light
search_enabled: false
heading_anchors: true
nav_enabled: false

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax